### ISSUE TITLE
Invalid Hook Call

### ISSUE THREAD

**Issue by iandjx** [TSTMKRSAfrica/nextjs-ab-test#6]
I've tried running the example code but always get an invalid hook call.

https://stackblitz.com/edit/nextjs-ab-test-ts?devtoolsheight=33&file=index.tsx

https://stackblitz.com/edit/nextjs-ab-test-js?devtoolsheight=33&file=src/App.js

**Comment by joselevelsup** [comment]
Hey @iandjx ! Thank you for opening an issue up. I can see why its not working for you. Your dependencies are using `react` and `react-dom` version 16.8.0. After updating the packages to the latest or 16.14.0, this package works as expected. I've attached a screenshot of a fork of your stackblitz. Please take a look. If you have any questions, I'll leave this issue open. 

![image](https://user-images.githubusercontent.com/10066172/111404189-b71fb880-86a4-11eb-8afe-494dfe52e064.png)

**Comment by iandjx** [comment]
thanks! Sorry, i didn't notice it earlier.

**Comment by joselevelsup** [comment]
That's no problem! I'll make sure to update our package and expect the peer dependencies include react 16.14 and above.

**Comment by iandjx** [comment]
The package breaks on React version 17.02

https://stackblitz.com/edit/nextjs-ab-test-ts?file=index.html

**Comment by iandjx** [comment]
The package breaks on React >17.0.0

https://stackblitz.com/edit/nextjs-ab-test-ts?file=package.json

**Comment by joselevelsup** [comment]
@iandjx I just opened your stackblitz and it appears to be working as intended. I attached a screenshot below. 

![image](https://user-images.githubusercontent.com/10066172/113090058-e4955780-91b6-11eb-864f-7316f4171c7a.png)

**Comment by iandjx** [comment]
ive updated the dependencies to the lates version. can you pleae check again?

**Comment by joselevelsup** [comment]
Hey sorry @iandjx for the late response. I see it breaking in your stackblitz. I'll take a look into it and see what's going on locally. (Most likely need to update the dependencies and `peerDependencies`). I'll get to it on sunday.

**Comment by joselevelsup** [comment]
@iandjx sorry for keeping you waiting. I finally updated the package to always include the latest react and react-dom package. I also tested it locally and forked your stackblitz (again) and made sure its using the latest version of this package and everything works as expected. Let me know if you have any more questions or problems.

**Comment by joselevelsup** [comment]
@iandjx have you tried it out?

**Comment by alenkas** [comment]
Hello. I had the same issue, my version of react and react-dom was `16.13.1` and `"@tstmkrs/nextjs-ab-test": "^0.0.4",`. So after upgrading react and react-dom to version `17.0.2` the error was gone. Thanks!

**Comment by iandjx** [comment]
Thanks for the update @joselevelsup ! sorry for the late reply. Everything works perfectly. :)
